name: Deploy to Xserver via FTP

on:
  push:
    branches:
      - gh-pages

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: FTP Deploy to Xserver
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.XSERVER_FTP_HOST }}
          username: ${{ secrets.XSERVER_FTP_USER }}
          password: ${{ secrets.XSERVER_FTP_PASS }}
          server-dir: /xs546083.xsrv.jp/public_html/life-navi/
          local-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
